### ISSUE TITLE
помогите((

### ISSUE THREAD

**Issue by namadeiru** [bomzheg/Shvatka#65]
при попытке запуска выдает ошибку:

ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Desktop\\Shvatka-master\\dist\\shvatka-0.1.0-py3-none-an
y.whl'
export : Имя "export" не распознано как имя командлета, функции, файла сценария или выполняемой программы. Проверьте правильность написания имени, а также наличие 
и правильность пути, после чего повторите попытку.
строка:1 знак:1
+ export BOT_PATH=$PWD
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (export:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by bomzheg** [comment]
export не поддерживается на windows=) это команда bash
